declare enum JUTRO_TOPICS {
    COMPONENT_LOADED = "JUTRO_TOPICS.COMPONENT_LOADED",
    VALUE_CHANGED = "JUTRO_TOPICS.VALUE_CHANGED",
    FIELD_BLUR = "JUTRO_TOPICS.FIELD_BLUR",
    ROUTE_CHANGED = "JUTRO_TOPICS.ROUTE_CHANGED",
    FETCH_REQUEST = "JUTRO_TOPICS.FETCH_REQUEST",
    FETCH_RESPONSE = "JUTRO_TOPICS.FETCH_RESPONSE",
    FETCH_ERROR = "JUTRO_TOPICS.FETCH_ERROR",
    UNKNOWN_ERROR = "JUTRO_TOPICS.UNKNOWN_ERROR",
    BUTTON_CLICKED = "JUTRO_TOPICS.BUTTON_CLICKED",
    LINK_CLICKED = "JUTRO_TOPICS.LINK_CLICKED"
}
export default JUTRO_TOPICS;
